name: Test Stuff

on: workflow_dispatch

env:
  UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}

jobs:
  testRunner:
    name: Print Stuff
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Print GITHUB_WORKSPACE
        shell: bash
        run: echo $GITHUB_WORKSPACE
        
      - name: DIR 1
        shell: bash
        run: mkdir test22
        
      - name: DIR LS
        shell: bash
        run: ls
        
      - name: DIR 2
        shell: bash
        run: mkdir /test
        
      - name: DIR LS 2
        shell: bash
        run: ls
